-- 将该建表 SQL 语句，添加到 dofast-module-channel-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "channel_customer" (
    "id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ref_oid" varchar NOT NULL,
    "pos_code" varchar NOT NULL,
    "mobile" varchar NOT NULL,
    "ref_type" varchar NOT NULL,
    "receiver_country" varchar NOT NULL,
    "receiver_state" varchar NOT NULL,
    "receiver_city" varchar NOT NULL,
    "receiver_district" varchar NOT NULL,
    "receiver_town" varchar NOT NULL,
    "receiver_id" varchar NOT NULL,
    "open_buyer_nick" varchar NOT NULL,
    "open_buyer_id" varchar NOT NULL,
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "creator" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "remark" varchar NOT NULL,
    "tenant_id" bigint NOT NULL,
    "address_id" int NOT NULL,
    "user_id" int NOT NULL,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
) COMMENT '交易客户';

-- 将该删表 SQL 语句，添加到 dofast-module-channel-biz 模块的 test/resources/sql/clean.sql 文件里
DELETE FROM "channel_customer";
