-- 将该建表 SQL 语句，添加到 dofast-module-channel-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "channel_order_goods" (
    "id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ref_oid" int NOT NULL,
    "ref_ol_id" varchar NOT NULL,
    "ref_spu_id" varchar NOT NULL,
    "ref_sku_id" varchar NOT NULL,
    "outer_id" varchar NOT NULL,
    "title" varchar NOT NULL,
    "standards" varchar NOT NULL,
    "total_sell_price" varchar NOT NULL,
    "total_price" varchar NOT NULL,
    "price" varchar NOT NULL,
    "sell_price" varchar NOT NULL,
    "total_fee" varchar NOT NULL,
    "single_fee" varchar NOT NULL,
    "num" int NOT NULL,
    "refund_status" varchar NOT NULL,
    "status" varchar NOT NULL,
    "pic_url" varchar NOT NULL,
    "is_free_gift" int NOT NULL,
    "tenant_id" int NOT NULL,
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "creator" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "deleted" bit NOT NULL DEFAULT FALSE,
    "user_id" int NOT NULL,
    PRIMARY KEY ("id")
) COMMENT '子订单';

-- 将该删表 SQL 语句，添加到 dofast-module-channel-biz 模块的 test/resources/sql/clean.sql 文件里
DELETE FROM "channel_order_goods";
