CREATE TABLE IF NOT EXISTS "channel_shop" (
      "id" varchar NOT NULL,
      "display_name" varchar NOT NULL,
      "name" varchar NOT NULL,
      "shop_nick" varchar NOT NULL,
      "shop_url" varchar NOT NULL,
      "shop_id" varchar NOT NULL,
      "shop_code" varchar NOT NULL,
      "channel" varchar NOT NULL,
      "sort_code" int NOT NULL,
      "deleted" bit NOT NULL DEFAULT FALSE,
      "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "creator" varchar DEFAULT '',
      "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      "updater" varchar DEFAULT '',
      "last_time" varchar NOT NULL,
      "remark" varchar NOT NULL,
      "tenant_id" bigint NOT NULL,
      PRIMARY KEY ("id")
) COMMENT '渠道店铺';

CREATE TABLE IF NOT EXISTS "order_remark" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "trade_order_id" bigint NOT NULL,
  "sort_code" int NOT NULL,
  "remark" varchar NOT NULL,
  "type" varchar NOT NULL,
  "sal_id" bigint,
  "creator" varchar DEFAULT '',
  "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  "updater" varchar DEFAULT '',
  "deleted" bit NOT NULL DEFAULT FALSE,
  "tenant_id" bigint NOT NULL,
  PRIMARY KEY ("id")
) COMMENT '订单备注';


CREATE TABLE IF NOT EXISTS "sales_order" (
     "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
     "sale_no" varchar,
     "title" varchar NOT NULL,
     "settlement" int,
     "price" varchar NOT NULL,
     "saler" int NOT NULL,
     "creator" varchar DEFAULT '',
     "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
     "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
     "updater" varchar DEFAULT '',
     "deleted" bit NOT NULL DEFAULT FALSE,
     "tenant_id" bigint NOT NULL,
     PRIMARY KEY ("id")
) COMMENT '销售订单';