CREATE TABLE IF NOT EXISTS "wiki_category" (
   "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "pid" bigint,
   "category_level" bit NOT NULL,
   "name" varchar NOT NULL,
   "creator" varchar DEFAULT '',
   "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
   "updater" varchar DEFAULT '',
   "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   "deleted" bit NOT NULL DEFAULT FALSE,
   "tenant_id" bigint NOT NULL,
   PRIMARY KEY ("id")
) COMMENT '首页的分类';

CREATE TABLE IF NOT EXISTS "wiki_courseware_file" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "courseware_id" bigint NOT NULL,
  "filename" varchar NOT NULL,
  "filepath" varchar NOT NULL,
  "file_size" varchar,
  "creator" varchar DEFAULT '',
  "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar DEFAULT '',
  "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE,
  "tenant_id" bigint NOT NULL,
  PRIMARY KEY ("id")
) COMMENT '课件文件的保存地址';

CREATE TABLE IF NOT EXISTS "wiki_lecturer" (
   "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "name" varchar NOT NULL,
   "direction" varchar NOT NULL,
   "picture" varchar NOT NULL,
   "creator" varchar DEFAULT '',
   "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
   "updater" varchar DEFAULT '',
   "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   "deleted" bit NOT NULL DEFAULT FALSE,
   "tenant_id" bigint NOT NULL,
   PRIMARY KEY ("id")
) COMMENT '讲师的信息	';

CREATE TABLE IF NOT EXISTS "wiki_coursewave" (
     "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
     "category_id" bigint,
     "courseware_name" varchar NOT NULL,
     "creator" varchar DEFAULT '',
     "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
     "updater" varchar DEFAULT '',
     "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
     "deleted" bit NOT NULL DEFAULT FALSE,
     "tenant_id" bigint NOT NULL,
     PRIMARY KEY ("id")
) COMMENT '首页知识列表的信息	';