-- 将该建表 SQL 语句，添加到 dofast-module-hr-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "hr_employee_basic" (
    "employee_photo" varchar NOT NULL,
    "employee_realname" varchar NOT NULL,
    "employee_sex" varchar NOT NULL,
    "employee_married" varchar NOT NULL,
    "employee_politics" varchar NOT NULL,
    "employee_nativeplace" varchar NOT NULL,
    "employee_birthday" varchar NOT NULL,
    "employee_height" varchar NOT NULL,
    "household_province_id" int NOT NULL,
    "household_province_name" varchar NOT NULL,
    "household_nature" varchar NOT NULL,
    "household_city_id" int NOT NULL,
    "household_address" varchar NOT NULL,
    "household_city_name" varchar NOT NULL,
    "employee_weight" varchar NOT NULL,
    "bloodtype" varchar NOT NULL,
    "education_name" varchar NOT NULL,
    "education" varchar NOT NULL,
    "emails" varchar NOT NULL,
    "qq" int NOT NULL,
    "id_no" varchar NOT NULL,
    "phone" int NOT NULL,
    "card_name" varchar NOT NULL,
    "card_no" varchar NOT NULL,
    "card_address" varchar NOT NULL,
    "now_province_id" int NOT NULL,
    "now_province_name" varchar NOT NULL,
    "now_province_address" varchar NOT NULL,
    "now_city_id" int NOT NULL,
    "now_city_name" varchar NOT NULL,
    "urgent_name_one" varchar NOT NULL,
    "urgent_name_one_phone" int NOT NULL,
    "character" varchar NOT NULL,
    "specialty" varchar NOT NULL,
    "status" varchar NOT NULL,
    "remark" varchar NOT NULL,
    "dep_id" int NOT NULL,
    "dep_name" varchar NOT NULL,
    "position_id" int NOT NULL,
    "position_name" varchar NOT NULL,
    "nick_name" varchar NOT NULL,
    "nick_img" varchar NOT NULL,
    "social_payment_time" varchar NOT NULL,
    "date_of_birth_time" varchar NOT NULL,
    "work_age" varchar NOT NULL,
    "work_level" varchar NOT NULL,
    "entry_time" varchar NOT NULL,
    "worker_time" varchar NOT NULL,
    "work_name" varchar NOT NULL,
    "creator" int DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" int DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" int NOT NULL,
    "id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ethnic" varchar NOT NULL,
    PRIMARY KEY ("id")
) COMMENT '员工基本信息表';

-- 将该建表 SQL 语句，添加到 dofast-module-hr-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "hr_commissionrule" (
    "id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "month" varchar NOT NULL,
    "account" varchar NOT NULL,
    "sale" varchar NOT NULL,
    "line" varchar NOT NULL,
    "creator" int DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" int DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" int NOT NULL,
    PRIMARY KEY ("id")
) COMMENT '提成规则';

-- 将该建表 SQL 语句，添加到 dofast-module-hr-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "hr_employee_education" (
    "education_school" varchar NOT NULL,
    "education_specialty" varchar NOT NULL,
    "education_honor" varchar NOT NULL,
    "education_starttime" varchar NOT NULL,
    "education_endtime" varchar NOT NULL,
    "creator" int DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" int DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" int NOT NULL,
    "id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    PRIMARY KEY ("id")
) COMMENT '员工教育培训经历';

-- 将该建表 SQL 语句，添加到 dofast-module-hr-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "hr_employee_familes" (
    "familes_name" varchar NOT NULL,
    "familes_realtion" varchar NOT NULL,
    "familes_workunit" varchar NOT NULL,
    "familes_workplace" varchar NOT NULL,
    "familes_phone" int NOT NULL,
    "creator" int DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" int DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" int NOT NULL,
    "id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    PRIMARY KEY ("id")
) COMMENT '员工家庭成员';

-- 将该建表 SQL 语句，添加到 dofast-module-hr-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "hr_employee_file" (
    "id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "id_card_front" varchar NOT NULL,
    "id_card_back" varchar NOT NULL,
    "graduation_certificate" varchar NOT NULL,
    "degree_certificate" varchar NOT NULL,
    "resignation_certificate" varchar NOT NULL,
    "bank_card" varchar NOT NULL,
    "one_inch_photo" varchar NOT NULL,
    "residence_permit" varchar NOT NULL,
    "signing_commitment_letter" varchar NOT NULL,
    "qualification" varchar NOT NULL,
    "participation_certificate" varchar NOT NULL,
    "physical_certificate" varchar,
    "creator" int DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" int DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" int NOT NULL,
    PRIMARY KEY ("id")
) COMMENT '员工信息文件表';

-- 将该建表 SQL 语句，添加到 dofast-module-hr-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "hr_salary" (
    "id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "order_flow_no" varchar NOT NULL,
    "detail_no" varchar NOT NULL,
    "sn" varchar NOT NULL,
    "month" varchar NOT NULL,
    "account" varchar NOT NULL,
    "company" int NOT NULL,
    "dept" int NOT NULL,
    "basic" varchar NOT NULL,
    "performance" varchar NOT NULL,
    "bonus" varchar NOT NULL,
    "allowance" varchar NOT NULL,
    "exemption" varchar NOT NULL,
    "deduction" varchar NOT NULL,
    "deserved" varchar NOT NULL,
    "actual" varchar NOT NULL,
    "company_ssf" varchar NOT NULL,
    "company_hpf" varchar NOT NULL,
    "cur_taxable_income" varchar NOT NULL,
    "taxable_income" varchar NOT NULL,
    "tax_payable" varchar NOT NULL,
    "tax_paid" varchar NOT NULL,
    "tax" varchar NOT NULL,
    "confirmer" varchar,
    "confirm_time" varchar,
    "granter" varchar,
    "grant_time" varchar,
    "desc" varchar NOT NULL,
    "status" varchar NOT NULL,
    "creator" int DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" int DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" int NOT NULL,
    PRIMARY KEY ("id")
) COMMENT '工资总表';

-- 将该建表 SQL 语句，添加到 dofast-module-hr-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "hr_employee_workhistory" (
    "company_name" varchar NOT NULL,
    "treatment" int NOT NULL,
    "treatment_post" varchar NOT NULL,
    "reason_for_leave" varchar NOT NULL,
    "creator" int DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" int DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" int NOT NULL,
    "id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    PRIMARY KEY ("id")
) COMMENT '员工工作经历';

-- 将该建表 SQL 语句，添加到 dofast-module-hr-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "hr_salarycommission" (
    "id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "salary" int NOT NULL,
    "type" varchar NOT NULL,
    "line" varchar NOT NULL,
    "amount" varchar NOT NULL,
    "rate" varchar NOT NULL,
    "commission" varchar NOT NULL,
    "desc" varchar NOT NULL,
    "creator" int DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" int DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" int NOT NULL,
    PRIMARY KEY ("id")
) COMMENT '绩效工资';

-- 将该建表 SQL 语句，添加到 dofast-module-hr-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "hr_salarydetail" (
    "id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "salary" int NOT NULL,
    "item" varchar NOT NULL,
    "type" varchar NOT NULL,
    "amount" varchar NOT NULL,
    "desc" varchar NOT NULL,
    "creator" int DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" int DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" int NOT NULL,
    PRIMARY KEY ("id")
) COMMENT '工资明细表';

-- 将该建表 SQL 语句，添加到 dofast-module-hr-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "hr_tradecommission" (
    "id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "type" varchar NOT NULL,
    "sign_type" varchar NOT NULL,
    "sale_type" varchar NOT NULL,
    "trade" int NOT NULL,
    "contract" int NOT NULL,
    "account" varchar NOT NULL,
    "contribution" varchar NOT NULL,
    "rate" varchar NOT NULL,
    "amount" varchar NOT NULL,
    "desc" varchar NOT NULL,
    "creator" int DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" int DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" int NOT NULL,
    PRIMARY KEY ("id")
) COMMENT '工资提成表';