-- 将该建表 SQL 语句，添加到 dofast-module-system-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "system_express_electronicsheet" (
    "id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "site_id" int NOT NULL,
    "site_name" varchar NOT NULL,
    "template_name" varchar NOT NULL,
    "company_id" int NOT NULL,
    "company_name" varchar NOT NULL,
    "express_no" varchar NOT NULL,
    "customer_name" varchar NOT NULL,
    "customer_pwd" varchar NOT NULL,
    "send_site" varchar NOT NULL,
    "send_staff" varchar NOT NULL,
    "month_code" varchar NOT NULL,
    "postage_payment_method" varchar NOT NULL,
    "is_notice" varchar NOT NULL,
    "status" varchar NOT NULL,
    "is_default" varchar NOT NULL,
    "print_style" int NOT NULL,
    "createdby" varchar NOT NULL,
    "createddate" varchar NOT NULL,
    "editedby" varchar NOT NULL,
    "editeddate" varchar NOT NULL,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL,
    PRIMARY KEY ("id")
) COMMENT '电子面单';

-- 将该建表 SQL 语句，添加到 dofast-module-system-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "system_form" (
    "id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar NOT NULL,
    "description" varchar NOT NULL,
    "background" varchar NOT NULL,
    "label_width" int,
    "type" varchar,
    "status" int NOT NULL,
    "creator" bigint DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" bigint DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL,
    PRIMARY KEY ("id")
) COMMENT '系统表单表';

-- 将该建表 SQL 语句，添加到 dofast-module-system-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "system_form_item" (
    "id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "parent_id" bigint NOT NULL,
    "name" varchar NOT NULL,
    "field" varchar NOT NULL,
    "validator" varchar NOT NULL,
    "type" varchar NOT NULL,
    "props" varchar NOT NULL,
    "component_props" varchar NOT NULL,
    "dict_type" varchar NOT NULL,
    "default_value" varchar NOT NULL,
    "sort" int NOT NULL,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "creator" bigint DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" bigint DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "tenant_id" bigint NOT NULL,
    PRIMARY KEY ("id")
) COMMENT '字段';

-- 将该建表 SQL 语句，添加到 dofast-module-system-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "system_form_record" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "form_id" bigint NOT NULL,
    "value" varchar NOT NULL,
    "creator" bigint DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" bigint DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "tenant_id" bigint NOT NULL,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
) COMMENT '表单历史';

CREATE TABLE IF NOT EXISTS "system_express_company_template" (
     "companyId" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
     "site_id" int NOT NULL,
     "company_name" varchar NOT NULL,
     "logo" varchar NOT NULL,
     "url" varchar NOT NULL,
     "sort" int NOT NULL,
     "express_no" varchar NOT NULL,
     "express_no_kd100" varchar NOT NULL,
     "express_no_cainiao" varchar NOT NULL,
     "content_json" varchar,
     "background_image" varchar NOT NULL,
     "font_size" int NOT NULL,
     "width" int NOT NULL,
     "height" int NOT NULL,
     "scale" varchar NOT NULL,
     "is_electronicsheet" varchar NOT NULL,
     "print_style" varchar NOT NULL,
     "creator" varchar DEFAULT '',
     "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
     "updater" varchar DEFAULT '',
     "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
     "deleted" bit NOT NULL DEFAULT FALSE,
     "tenant_id" bigint,
     PRIMARY KEY ("company_id")
) COMMENT '系统物流公司表';

CREATE TABLE IF NOT EXISTS "system_express_company" (
    "id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "company_id" int NOT NULL,
    "company_name" varchar NOT NULL,
    "logo" varchar NOT NULL,
    "content_json" varchar,
    "background_image" varchar NOT NULL,
    "font_size" varchar NOT NULL,
    "width" varchar NOT NULL,
    "height" varchar NOT NULL,
    "scale" varchar NOT NULL,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint,
    "is_electronicsheet" varchar,
    "express_no" varchar NOT NULL,
    "express_no_diansan" varchar NOT NULL,
    "express_no_kd100" varchar NOT NULL,
    "express_no_cainiao" varchar NOT NULL,
    "print_style" varchar,
    PRIMARY KEY ("id")
) COMMENT '租户物流公司';

CREATE TABLE IF NOT EXISTS "system_config" (
   "id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "site_id" int NOT NULL,
   "app_module" varchar NOT NULL,
   "config_key" varchar NOT NULL,
   "value" varchar,
   "config_desc" varchar NOT NULL,
   "is_use" varchar NOT NULL,
   "creator" varchar DEFAULT '',
   "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
   "updater" varchar DEFAULT '',
   "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   "deleted" bit NOT NULL DEFAULT FALSE,
   "tenant_id" bigint NOT NULL,
   PRIMARY KEY ("id")
) COMMENT '租户配置表';
