-- 将该建表 SQL 语句，添加到 dofast-module-cal-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "cal_holiday" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "the_day" varchar,
    "holiday_type" varchar,
    "start_time" varchar,
    "end_time" varchar,
    "remark" varchar,
    "attr1" varchar,
    "attr2" varchar,
    "attr3" int,
    "attr4" int,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL,
    PRIMARY KEY ("id")
) COMMENT '节假日设置';

-- 将该建表 SQL 语句，添加到 dofast-module-cal-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "cal_plan" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "plan_code" varchar NOT NULL,
    "plan_name" varchar NOT NULL,
    "calendar_type" varchar,
    "start_date" varchar NOT NULL,
    "end_date" varchar NOT NULL,
    "shift_type" varchar,
    "shift_method" varchar,
    "shift_count" int,
    "status" varchar,
    "remark" varchar,
    "attr1" varchar,
    "attr2" varchar,
    "attr3" int,
    "attr4" int,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL,
    PRIMARY KEY ("id")
) COMMENT '排班计划表';

-- 将该建表 SQL 语句，添加到 dofast-module-cal-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "cal_plan_team" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "plan_id" bigint NOT NULL,
    "team_id" bigint NOT NULL,
    "team_code" varchar,
    "team_name" varchar,
    "remark" varchar,
    "attr1" varchar,
    "attr2" varchar,
    "attr3" int,
    "attr4" int,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL,
    PRIMARY KEY ("id")
) COMMENT '计划班组表';

-- 将该建表 SQL 语句，添加到 dofast-module-cal-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "cal_shift" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "plan_id" bigint NOT NULL,
    "order_num" int NOT NULL,
    "shift_name" varchar NOT NULL,
    "start_time" varchar NOT NULL,
    "end_time" varchar NOT NULL,
    "remark" varchar,
    "attr1" varchar,
    "attr2" varchar,
    "attr3" int,
    "attr4" int,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL,
    PRIMARY KEY ("id")
) COMMENT '计划班次表';

-- 将该建表 SQL 语句，添加到 dofast-module-cal-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "cal_team" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "team_code" varchar NOT NULL,
    "team_name" varchar NOT NULL,
    "calendar_type" varchar,
    "remark" varchar,
    "attr1" varchar,
    "attr2" varchar,
    "attr3" int,
    "attr4" int,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL,
    PRIMARY KEY ("id")
) COMMENT '班组表';

-- 将该建表 SQL 语句，添加到 dofast-module-cal-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "cal_teamshift" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "the_day" varchar NOT NULL,
    "team_id" bigint NOT NULL,
    "team_name" varchar,
    "shift_id" bigint NOT NULL,
    "shift_name" varchar,
    "order_num" int,
    "plan_id" bigint,
    "calendar_type" varchar,
    "shift_type" varchar,
    "remark" varchar,
    "attr1" varchar,
    "attr2" varchar,
    "attr3" int,
    "attr4" int,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL,
    PRIMARY KEY ("id")
) COMMENT '班组排班表';

-- 将该建表 SQL 语句，添加到 dofast-module-cal-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "cal_team_member" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "team_id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "user_name" varchar NOT NULL,
    "nick_name" varchar,
    "tel" varchar,
    "remark" varchar,
    "attr1" varchar,
    "attr2" varchar,
    "attr3" int,
    "attr4" int,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL,
    PRIMARY KEY ("id")
) COMMENT '班组成员表';